"""milestone 5 and 6: retrieval, ingestion, agents tables

Revision ID: f8698cb5abae
Revises: be0234931e65
Create Date: 2026-08-02 16:03:05.708859

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f8698cb5abae'
down_revision: str | None = 'be0234931e65'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.Text(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_executions_agent_name_started_at', 'agent_executions', ['agent_name', 'started_at'], unique=False)
    op.create_index('ix_agent_executions_org_started_at', 'agent_executions', ['organization_id', 'started_at'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('source_offset_start', sa.Integer(), nullable=False),
    sa.Column('source_offset_end', sa.Integer(), nullable=False),
    sa.Column('acl_permission_code', sa.Text(), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_code_chunks_document_chunk_index')
    )
    op.create_index('ix_code_chunks_content_tsv', 'code_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_code_chunks_org_project', 'code_chunks', ['organization_id', 'project_id'], unique=False)
    op.create_table('conversations_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('source_offset_start', sa.Integer(), nullable=False),
    sa.Column('source_offset_end', sa.Integer(), nullable=False),
    sa.Column('acl_permission_code', sa.Text(), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_conversations_chunks_document_chunk_index')
    )
    op.create_index('ix_conversations_chunks_content_tsv', 'conversations_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_conversations_chunks_org_project', 'conversations_chunks', ['organization_id', 'project_id'], unique=False)
    op.create_table('documentation_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('source_offset_start', sa.Integer(), nullable=False),
    sa.Column('source_offset_end', sa.Integer(), nullable=False),
    sa.Column('acl_permission_code', sa.Text(), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_documentation_chunks_document_chunk_index')
    )
    op.create_index('ix_documentation_chunks_content_tsv', 'documentation_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_documentation_chunks_org_project', 'documentation_chunks', ['organization_id', 'project_id'], unique=False)
    op.add_column('documents', sa.Column('acl_permission_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'acl_permission_code')
    op.drop_index('ix_documentation_chunks_org_project', table_name='documentation_chunks')
    op.drop_index('ix_documentation_chunks_content_tsv', table_name='documentation_chunks', postgresql_using='gin')
    op.drop_table('documentation_chunks')
    op.drop_index('ix_conversations_chunks_org_project', table_name='conversations_chunks')
    op.drop_index('ix_conversations_chunks_content_tsv', table_name='conversations_chunks', postgresql_using='gin')
    op.drop_table('conversations_chunks')
    op.drop_index('ix_code_chunks_org_project', table_name='code_chunks')
    op.drop_index('ix_code_chunks_content_tsv', table_name='code_chunks', postgresql_using='gin')
    op.drop_table('code_chunks')
    op.drop_index('ix_agent_executions_org_started_at', table_name='agent_executions')
    op.drop_index('ix_agent_executions_agent_name_started_at', table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
